;
; Cask
; Emacs package installer
; Version 1.0
;
; Created by Takashi Higasa
; Last Modified 2017/02/15



;; package source
(source gnu)
(source melpa)
(source marmalade)


;; install package
(depends-on "initchart" :git "http://github.com/yuttie/initchart.git")

;; system tools
(depends-on "init-loader")
(depends-on "auto-complete")
(depends-on "git-gutter")
(depends-on "minimap")
(depends-on "recentf-ext")
(depends-on "session")
(depends-on "magit")

;; helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-descbinds")


;; editor tools
(depends-on "undo-tree")
(depends-on "yasnippet")
(depends-on "git-gutter")
(depends-on "migemo")
(depends-on "expand-region")

;; mode
(depends-on "markdown-mode")
(depends-on "flycheck")